### ISSUE TITLE
Missing dependence on pysynphot

### ISSUE THREAD

**Issue by rmjarvis** [mperrin/poppy#266]
I've been looking at the new WebbPSF code for rendering WFIRST PSF images [here](https://wfirst.gsfc.nasa.gov/science/WFIRST_Reference_Information.html), and running their script, I got an ImportError from poppy:
```
$ python wim_psf_basic_f0v_even.py 
Script to generate WFIRST imaging PSFs for each SCA in the FPA
Please ensure that updates to the zernike file are copied to 
{$HOME}/Projects/WebbPSF/webbpsf-data/WFI/wim_zernikes_cycle8.csv
Traceback (most recent call last):
  File "wim_psf_basic_f0v_even.py", line 139, in <module>
    s_src = webbpsf.specFromSpectralType(sp_type, catalog='phoenix')
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/poppy/utils.py", line 1433, in specFromSpectralType
    import pysynphot
ModuleNotFoundError: No module named 'pysynphot'
```
Installing pysynphot fixed the problem (or at least got farther before hitting a different error), but it seems like poppy is missing a dependence on pysynphot in the pip and/or conda specification.  (I installed webbpsf via conda, which in turn installed poppy.)

**Comment by mperrin** [comment]
Hi @rmjarvis, could you please re-file this issue on the spacetelescope repo: https://github.com/spacetelescope/webbpsf

That’s our main development repository now and is the best place to file issues. Thanks much for this report!

**Comment by rmjarvis** [comment]
OK!
